package localizationimpl

var English = map[string]interface{}{
	"firstName":           "first name",
	"lastName":            "last name",
	"phone":               "phone",
	"password":            "password",
	"confirmPassword":     "confirm password",
	"isAcceptTerms":       "terms and conditions",
	"corporation":         "corporation",
	"cin":                 "cin",
	"installationRequest": "installation request",
	"bid":                 "bid",
	"errors": map[string]interface{}{
		"generic":                "an error occurred, please try again.",
		"numeric":                "The {0} should be a numeric value.",
		"fileRequired":           "File is required.",
		"minimumLength":          "The {0} Len must bigger than 7 characters.",
		"containsLowercase":      "The {0} should contain lowercase.",
		"containsUppercase":      "The {0} should contain uppercase.",
		"containsNumber":         "The {0} should contain number.",
		"containsSpecialChar":    "The {0} should contain special character.",
		"alreadyRegistered":      "Has been already registered with this {0}",
		"required":               "Field {0} required to fill",
		"e164":                   "Phone number u have entered is not correct",
		"eqfield":                "Password and {0} are not the same.",
		"eq":                     "Field {0} should be true.",
		"Expired":                "OTP is expired.",
		"invalid":                "OTP is invalid.",
		"notRegistered":          "You have to register first.",
		"invalidAuthCredentials": "Username and password not matched",
		"expiredAuthToken":       "Your token has been expired. Please log in again.",
		"invalidAuthToken":       "There is a problem with your token.",
		"unauthorized":           "Please login first.",
		"awaitingApproval":       "Your account is awaiting admin approval.",
		"rejected":               "Your account has been rejected by admin.",
		"notExist":               "This {0} does not exist.",
		"alreadyExist":            "This {0} already exists.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":            "Registration Successful! Please check your messages to verify your account and complete the registration process.",
		"phoneVerification":       "Your phone has been successfully verified.",
		"login":                   "Logged in successfully.",
		"corporationRegister":     "Your Registration request has been sent successfully. Please wait for the admin to approve your request.",
		"getInstallationRequests": "Installation requests fetched successfully.",
		"setBid":                  "Your bid has been successfully registered.",
		"cancelBid":               "Your bid has been successfully canceled.",
		"getBids":                 "Bids fetched successfully.",
		"updateContactInfo":       "Contact information updated successfully.",
		"addAddress":              "Address added successfully.",
		"editAddress":             "Address edited successfully.",
		"deleteAddress":           "Address deleted successfully.",
	},
}
