package localizationimpl

var English = map[string]interface{}{
	"firstName":       "first name",
	"lastName":        "last name",
	"phone":           "phone",
	"password":        "password",
	"confirmPassword": "confirm password",
	"isAcceptTerms":   "terms and conditions",
	"errors": map[string]interface{}{
		"generic":                "an error occurred, please try again.",
		"numeric":                "The {0} should be a numeric value.",
		"minimumLength":          "The {0} Len must bigger than 7 characters.",
		"containsLowercase":      "The {0} should contain lowercase.",
		"containsUppercase":      "The {0} should contain uppercase.",
		"containsNumber":         "The {0} should contain number.",
		"containsSpecialChar":    "The {0} should contain special character.",
		"alreadyRegistered":      "Has been already registered with this {0}",
		"required":               "Field {0} required to fill",
		"e164":                   "Phone number u have entered is not correct",
		"eqfield=Password":       "Password and {0} are not the same.",
		"eq":                     "Field {0} should be true.",
		"otpExpired":             "OTP is expired.",
		"invalidOTP":             "OTP is invalid.",
		"notRegistered":          "You have to register first.",
		"invalidAuthCredentials": "Username and password not matched",
		"expiredAuthToken":       "Your token has been expired. Please log in again.",
		"invalidAuthToken":       "There is a problem with your token.",
		"unauthorized":           "Please login first.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":      "Registration Successful! Please check your messages to verify your account and complete the registration process.",
		"phoneVerification": "Your phone has been successfully verified.",
		"login":             "Logged in successfully.",
		"forgotPassword":    "Please check your messages to verify your phone number.",
	},
}
