package localizationimpl

var English = map[string]interface{}{
	"firstName":           "first name",
	"lastName":            "last name",
	"phone":               "phone",
	"password":            "password",
	"confirmPassword":     "confirm password",
	"isAcceptTerms":       "terms and conditions",
	"corporation":         "corporation",
	"nationalID":          "national ID",
	"registrationNumber":  "registration number",
	"iban":                "iban",
	"installationRequest": "installation request",
	"bid":                 "bid",
	"user":                "user",
	"address":             "address",
	"name":                "name",
	"province":            "province",
	"city":                "city",
	"page":                "page",
	"contactType":         "contact type",
	"room":                "chat room",
	"NotificationType":    "notification type",
	"Notification":        "notification",
	"panelName":           "panel name",
	"panel":               "panel",
	"maintenanceRequest":  "maintenance request",
	"email":               "email",
	"errors": map[string]interface{}{
		"generic":                "an error occurred, please try again.",
		"numeric":                "The {0} should be a numeric value.",
		"fileRequired":           "File is required.",
		"minimumLength":          "The {0} Len must bigger than 7 characters.",
		"containsLowercase":      "The {0} should contain lowercase.",
		"containsUppercase":      "The {0} should contain uppercase.",
		"containsNumber":         "The {0} should contain number.",
		"containsSpecialChar":    "The {0} should contain special character.",
		"alreadyRegistered":      "Has been already registered with this {0}",
		"required":               "Field {0} required to fill",
		"e164":                   "Phone number u have entered is not correct",
		"eqfield":                "Password and {0} are not the same.",
		"eq":                     "Field {0} should be true.",
		"Expired":                "OTP is expired.",
		"email":                  "Email format is wrong.",
		"invalid":                "OTP is invalid.",
		"notRegistered":          "You have to register first.",
		"invalidAuthCredentials": "Username and password not matched",
		"expiredAuthToken":       "Your token has been expired. Please log in again.",
		"invalidAuthToken":       "There is a problem with your token.",
		"unauthorized":           "Please login first.",
		"awaitingApproval":       "Your account is awaiting admin approval.",
		"rejected":               "Your account has been rejected by admin.",
		"notExist":               "This {0} does not exist.",
		"alreadyExist":           "This {0} already exists.",
		"notFound":               "This {0} not found.",
		"notVerified":            "You have to verify your account first.",
		"rateLimitExceed":        "Rate limit exceeded. try again later.",
		"installRateLimit":       "Active installation requests has been exceeded the limit.",
		"forbiddenError":         "Forbidden: Access to {0} is not allowed",
		"forbiddenStatus":        "Cannot do this action with this status.",
		"pending":                "Your request is pending.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":              "Registration Successful! Please check your messages to verify your account and complete the registration process.",
		"phoneVerification":         "Your phone has been successfully verified.",
		"login":                     "Logged in successfully.",
		"corporationRegister":       "Your Registration request has been sent successfully. Please wait for the admin to approve your request.",
		"getInstallationRequests":   "Installation requests fetched successfully.",
		"setBid":                    "Your bid has been successfully registered.",
		"cancelBid":                 "Your bid has been successfully canceled.",
		"getBids":                   "Bids fetched successfully.",
		"updateContactInfo":         "Contact information updated successfully.",
		"addAddress":                "Address added successfully.",
		"editAddress":               "Address edited successfully.",
		"deleteAddress":             "Address deleted successfully.",
		"changePassword":            "Password changed successfully.",
		"forgotPassword":            "Please check your messages to verify your phone number.",
		"resetPassword":             "Password reset successfully.",
		"installationRequest":       "Installation request has been successfully stored.",
		"createAddress":             "Address created successfully.",
		"refreshToken":              "Your session has been successfully refreshed.",
		"addCorporationCertificate": "Your certificate has been uploaded successfully.",
		"readNotification":          "notification marked as read",
		"updateNotificationSetting": "notification setting has been updated successfully",
		"addPanel":                  "Panel added successfully.",
		"maintenanceRequest":        "Maintenance request has been successfully stored.",
		"addMaintenanceRecord":      "Maintenance record has been successfully added.",
		"maintenanceRequestHandled": "Maintenance request has been successfully handled.",
		"completeRegister":          "Your registration has been completed successfully.",
		"emailVerification":         "Your email has been successfully verified.",
		"updateProfile":             "Profile has been updated successfully",
	},
	"emailSubject": map[string]interface{}{
		"emailConfirmation": "Verify Your Email Address",
	},
}
