package localizationimpl

var Persian = map[string]interface{}{
	"firstName":           "نام",
	"lastName":            "نام خانوادگی",
	"phone":               "شماره تماس",
	"password":            "رمز عبور",
	"confirmPassword":     "تایید رمز عیور",
	"isAcceptTerms":       "تایید شرایط و مقررات",
	"corporation":         "شرکت",
	"cin":                 "شناسه ملی",
	"installationRequest": "درخواست نصب",
	"bid":                 "پیشنهاد",
	"user":                "کاربر",
	"address":             "آدرس",
	"name":                "نام",
	"province":            "استان",
	"city":                "شهر",
	"errors": map[string]interface{}{
		"generic":                "خطایی رخ داده است، لطفا دوباره تلاش کنید.",
		"numeric":                "`{0}` باید عدد باشد.",
		"fileRequired":           "وارد کردن فایل اجباری است.",
		"minimumLength":          "باید از 7 کاراکتر بیشتر باشد.",
		"containsLowercase":      "باید حتما دارای حرف کوچک باشد.",
		"containsUppercase":      "باید حتما دارای حرف بزرگ باشد.",
		"containsNumber":         "باید حتما دارای عدد باشد.",
		"containsSpecialChar":    "باید حتما دارای حروف خاص باشد.",
		"alreadyRegistered":      "قبلا با این {0} ثبت نام کرده است.",
		"required":               "بخش {0} باید کامل شود.",
		"e164":                   "شماره تلفن به درستی ثبت نشده است.",
		"eqfield":                "رمز عبور و {0} مطابقت ندارند.",
		"eq":                     "مقدار {0 باید درست باشد}",
		"Expired":                "رمز یکبار مصرف شما منقضی شده است.",
		"invalid":                "رمز یکبار مصرف وارد شده اشتباه است.",
		"notRegistered":          "ابتدا باید در سایت ثبت نام کنید.",
		"invalidAuthCredentials": "نام کاربری و رمز عبور تطابق ندارند.",
		"expiredAuthToken":       "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"invalidAuthToken":       "در توکن ورود شما اشکالی وجود دارد.",
		"unauthorized":           "ابتدا باید وارد شوید.",
		"awaitingApproval":       "حساب شما در انتظار تایید ادمین است.",
		"rejected":               "حساب شما توسط ادمین رد شده است.",
		"notExist":               "این {0} وجود ندارد.",
		"alreadyExist":           "این {0} قبلا وجود داشته است.",
		"notFound":               "این {0} پیدا نشد.",
		"notVerified":            "باید ابتدا حساب خود را فعال کنید.",
		"rateLimitExceed":        "بیشتر از حد مجاز درخواست ثبت کرده اید.",
		"installRateLimit":       "تعداد درخواست های فعال شما از حدنساب عبور کرده است.",
		"createAddress":          "آدرس مورد نظر با موفقیت اضافه شد.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":            "ثبت نام موفق بود! لطفاً پیامک های خود را بررسی کنید تا حساب خود را تأیید کرده و فرآیند ثبت نام را تکمیل نمایید.",
		"phoneVerification":       "شماره شما با موفقیت تایید شد.",
		"login":                   "شما با موفقیت وارد شدید.",
		"corporationRegister":     "درخواست ثبت نام شما با موفقیت ارسال شد. لطفا منتظر بمانید تا ادمین درخواست شما را تایید کند.",
		"getInstallationRequests": "درخواست های نصب با موفقیت دریافت شد.",
		"setBid":                  "پیشنهاد شما با موفقیت ثبت شد.",
		"cancelBid":               "پیشنهاد شما با موفقیت لغو شد.",
		"getBids":                 "پیشنهادات با موفقیت دریافت شد.",
		"updateContactInfo":       "اطلاعات تماس با موفقیت به روز شد.",
		"addAddress":              "آدرس با موفقیت اضافه شد.",
		"editAddress":             "آدرس با موفقیت ویرایش شد.",
		"deleteAddress":           "آدرس با موفقیت حذف شد.",
		"changePassword":          "رمز عبور با موفقیت تغییر کرد.",
		"forgotPassword":          "لطفا پیامک های خود را بررسی کنید تا تلفن خود را تایید نمایید .",
		"resetPassword":           "گذرواژه با موفقیت تغییر کرد.",
		"installationRequest":     "درخواست نصب شما با موفقیت ثبت شد.",
	},
}
