package localizationimpl

var Persian = map[string]interface{}{
	"firstName":       "نام",
	"lastName":        "نام خانوادگی",
	"phone":           "شماره تماس",
	"password":        "رمز عبور",
	"confirmPassword": "تایید رمز عیور",
	"isAcceptTerms":   "تایید شرایط و مقررات",
	"corporation":     "شرکت",
	"cin":             "شناسه ملی",
	"installationRequest": "درخواست نصب",	
	"bidder":          "متقاضی",
	"errors": map[string]interface{}{
		"generic":                "خطایی رخ داده است، لطفا دوباره تلاش کنید.",
		"numeric":                "`{0}` باید عدد باشد.",
		"fileRequired":           "وارد کردن فایل اجباری است.",
		"minimumLength":          "باید از 7 کاراکتر بیشتر باشد.",
		"containsLowercase":      "باید حتما دارای حرف کوچک باشد.",
		"containsUppercase":      "باید حتما دارای حرف بزرگ باشد.",
		"containsNumber":         "باید حتما دارای عدد باشد.",
		"containsSpecialChar":    "باید حتما دارای حروف خاص باشد.",
		"alreadyRegistered":      "قبلا با این {0} ثبت نام کرده است.",
		"required":               "بخش {0} باید کامل شود.",
		"e164":                   "شماره تلفن به درستی ثبت نشده است.",
		"eqfield":                "رمز عبور و {0} مطابقت ندارند.",
		"eq=true":                "مقدار {0 باید درست باشد}",
		"Expired":             "رمز یکبار مصرف شما منقضی شده است.",
		"invalid":             "رمز یکبار مصرف وارد شده اشتباه است.",
		"notRegistered":          "ابتدا باید در سایت ثبت نام کنید.",
		"invalidAuthCredentials": "نام کاربری و رمز عبور تطابق ندارند.",
		"expiredAuthToken":       "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"invalidAuthToken":       "در توکن ورود شما اشکالی وجود دارد.",
		"unauthorized":           "ابتدا باید وارد شوید.",
		"notExist":             "این {0} وجود ندارد.",
		"notActive":             "حساب شما فعال نیست.",
		"pending":               "در انتظار تایید",
	},
	"successMessage": map[string]interface{}{
		"userRegister":            "ثبت نام موفق بود! لطفاً پیامک های خود را بررسی کنید تا حساب خود را تأیید کرده و فرآیند ثبت نام را تکمیل نمایید.",
		"phoneVerification":       "شماره شما با موفقیت تایید شد.",
		"login":                   "شما با موفقیت وارد شدید.",
		"corporationRegister":     "درخواست ثبت نام شما با موفقیت ارسال شد. لطفا منتظر بمانید تا ادمین درخواست شما را تایید کند.",
		"getInstallationRequests": "درخواست های نصب با موفقیت دریافت شد.",
		"setBid":                  "پیشنهاد شما با موفقیت ثبت شد.",
		"cancelBid":               "پیشنهاد شما با موفقیت لغو شد.",
		"getBids":                 "پیشنهادات با موفقیت دریافت شد.",
	},
}
