// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/BargheNo/Backend/bootstrap"
	"github.com/BargheNo/Backend/internal/application/adapter/jwt"
	"github.com/BargheNo/Backend/internal/application/adapter/localization"
	"github.com/BargheNo/Backend/internal/application/adapter/logger"
	"github.com/BargheNo/Backend/internal/application/adapter/metrics"
	"github.com/BargheNo/Backend/internal/application/service"
	"github.com/BargheNo/Backend/internal/application/service/communication"
	"github.com/BargheNo/Backend/internal/application/service/interfaces"
	"github.com/BargheNo/Backend/internal/domain/logger"
	"github.com/BargheNo/Backend/internal/domain/metrics"
	"github.com/BargheNo/Backend/internal/domain/repository/postgres"
	"github.com/BargheNo/Backend/internal/domain/repository/redis"
	"github.com/BargheNo/Backend/internal/infrastructure/cin"
	"github.com/BargheNo/Backend/internal/infrastructure/database"
	"github.com/BargheNo/Backend/internal/infrastructure/repository/postgres"
	"github.com/BargheNo/Backend/internal/infrastructure/repository/redis"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/corporation"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/user"
	"github.com/BargheNo/Backend/internal/presentation/middleware"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config) (*Application, error) {
	bootstrapDatabase := ProvideDBConfig(container)
	postgresDatabase := database.NewPostgresDatabase(bootstrapDatabase)
	redis := ProvideRDBConfig(container)
	redisDatabase := database.NewRedisDatabase(redis)
	wireDatabase := &Database{
		DB:  postgresDatabase,
		RDB: redisDatabase,
	}
	constants := ProvideConstants(container)
	otp := ProvideOTPConfig(container)
	userCacheRepository := cacherepositoryimpl.NewUserCacheRepository(redisDatabase)
	otpService := serviceimpl.NewOTPService(otp, userCacheRepository)
	smsGateway := ProvideSMSGatewayConfig(container)
	smsTemplates := ProvideSMSTemplates(container)
	smsService := communicationService.NewSMSService(smsGateway, smsTemplates)
	keyManager := jwtimpl.NewJWTKeyManager()
	jwtKeysPath := ProvideJWTKeysPath(container)
	jwtService := serviceimpl.NewJWTService(keyManager, jwtKeysPath)
	userRepository := repositoryimpl.NewUserRepository()
	userService := serviceimpl.NewUserService(constants, otpService, smsService, jwtService, userRepository, userCacheRepository, postgresDatabase)
	generalUserController := user.NewGeneralUserController(constants, userService)
	corporationRepository := repositoryimpl.NewCorporationRepository()
	cinService := cinimpl.NewCINService()
	corporationService := serviceimpl.NewCorporationService(constants, jwtService, postgresDatabase, corporationRepository, cinService)
	generalCorporationController := corporation.NewGeneralCorporationController(constants, corporationService)
	generalControllers := &GeneralControllers{
		UserController:        generalUserController,
		CorporationController: generalCorporationController,
	}
	bidRepository := repositoryimpl.NewBidRepository()
	bidService := serviceimpl.NewBidService(constants, jwtService, postgresDatabase, bidRepository, corporationService)
	memberCorporationController := corporation.NewMemberCorporationController(constants, corporationService, bidService)
	memberControllers := &MemberControllers{
		CorporationController: memberCorporationController,
	}
	controllers := &Controllers{
		General: generalControllers,
		Member:  memberControllers,
	}
	corsMiddleware := middleware.NewCorsMiddleware()
	recoveryMiddleware := middleware.NewRecovery(constants)
	translator := localizationimpl.NewTranslationService()
	localizationMiddleware := middleware.NewLocalization(constants, translator)
	rateLimit := ProvideRateLimitConfig(container)
	rateLimitMiddleware := middleware.NewRateLimit(rateLimit)
	logger := ProvideLoggerConfig(container)
	loggerimplLogger, err := loggerimpl.NewLogger(logger, constants)
	if err != nil {
		return nil, err
	}
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerimplLogger)
	metrics := ProvideMetrics(constants)
	prometheusMetrics := metricsimpl.NewPrometheusMetrics(metrics)
	prometheusMiddleware := middleware.NewPrometheusMiddleware(prometheusMetrics)
	authMiddleware := middleware.NewAuthMiddleware(constants, jwtService, postgresDatabase)
	middlewares := &Middlewares{
		CORS:         corsMiddleware,
		Recovery:     recoveryMiddleware,
		Localization: localizationMiddleware,
		RateLimit:    rateLimitMiddleware,
		Logger:       loggerMiddleware,
		Prometheus:   prometheusMiddleware,
		Auth:         authMiddleware,
	}
	application := NewApplication(wireDatabase, controllers, middlewares)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(database.NewPostgresDatabase, database.NewRedisDatabase, wire.Bind(new(database.Database), new(*database.PostgresDatabase)), wire.Bind(new(database.Cache), new(*database.RedisDatabase)), wire.Struct(new(Database), "*"))

var RepositoryProviderSet = wire.NewSet(repositoryimpl.NewUserRepository, cacherepositoryimpl.NewUserCacheRepository, repositoryimpl.NewCorporationRepository, repositoryimpl.NewBidRepository, wire.Bind(new(repository.UserRepository), new(*repositoryimpl.UserRepository)), wire.Bind(new(cacherepository.UserCacheRepository), new(*cacherepositoryimpl.UserCacheRepository)), wire.Bind(new(repository.CorporationRepository), new(*repositoryimpl.CorporationRepository)), wire.Bind(new(repository.BidRepository), new(*repositoryimpl.BidRepository)))

var ServiceProviderSet = wire.NewSet(serviceimpl.NewUserService, serviceimpl.NewOTPService, communicationService.NewSMSService, serviceimpl.NewJWTService, serviceimpl.NewCorporationService, cinimpl.NewCINService, serviceimpl.NewBidService, wire.Bind(new(service.UserService), new(*serviceimpl.UserService)), wire.Bind(new(service.OTPService), new(*serviceimpl.OTPService)), wire.Bind(new(service.SMSService), new(*communicationService.SMSService)), wire.Bind(new(service.JWTService), new(*serviceimpl.JWTService)), wire.Bind(new(service.CorporationService), new(*serviceimpl.CorporationService)), wire.Bind(new(service.CINService), new(*cinimpl.CINService)), wire.Bind(new(service.BidService), new(*serviceimpl.BidService)))

var AdapterProviderSet = wire.NewSet(localizationimpl.NewTranslationService, loggerimpl.NewLogger, jwtimpl.NewJWTKeyManager, metricsimpl.NewPrometheusMetrics, wire.Bind(new(logger.Logger), new(*loggerimpl.Logger)), wire.Bind(new(metrics.MetricsClient), new(*metricsimpl.PrometheusMetrics)))

var GeneralControllerProviderSet = wire.NewSet(user.NewGeneralUserController, corporation.NewGeneralCorporationController, wire.Struct(new(GeneralControllers), "*"))

var MemberControllerProviderSet = wire.NewSet(corporation.NewMemberCorporationController, wire.Struct(new(MemberControllers), "*"))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewareProviderSet = wire.NewSet(middleware.NewCorsMiddleware, middleware.NewRecovery, middleware.NewLocalization, middleware.NewRateLimit, middleware.NewLoggerMiddleware, middleware.NewPrometheusMiddleware, middleware.NewAuthMiddleware, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Config) *bootstrap.Constants {
	return container.Constants
}

func ProvideLoggerConfig(container *bootstrap.Config) *bootstrap.Logger {
	return &container.Env.Logger
}

func ProvideRateLimitConfig(container *bootstrap.Config) *bootstrap.RateLimit {
	return &container.Env.RateLimit
}

func ProvideDBConfig(container *bootstrap.Config) *bootstrap.Database {
	return &container.Env.PrimaryDB
}

func ProvideRDBConfig(container *bootstrap.Config) *bootstrap.Redis {
	return &container.Env.PrimaryRedis
}

func ProvideOTPConfig(container *bootstrap.Config) *bootstrap.OTP {
	return &container.Env.OTP
}

func ProvideSMSGatewayConfig(container *bootstrap.Config) *bootstrap.SMSGateway {
	return &container.Env.SMSGateway
}

func ProvideSMSTemplates(container *bootstrap.Config) *bootstrap.SMSTemplates {
	return &container.Constants.SMSTemplates
}

func ProvideJWTKeysPath(container *bootstrap.Config) *bootstrap.JWTKeysPath {
	return &container.Constants.JWTKeysPath
}

func ProvideMetrics(container *bootstrap.Constants) *bootstrap.Metrics {
	return &container.Metrics
}

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	RepositoryProviderSet,
	ServiceProviderSet,
	AdapterProviderSet,
	GeneralControllerProviderSet,
	MemberControllerProviderSet,
	ControllersProviderSet,
	MiddlewareProviderSet,
	ProvideConstants,
	ProvideLoggerConfig,
	ProvideRateLimitConfig,
	ProvideDBConfig,
	ProvideRDBConfig,
	ProvideOTPConfig,
	ProvideSMSGatewayConfig,
	ProvideSMSTemplates,
	ProvideJWTKeysPath,
	ProvideMetrics,
)

type Database struct {
	DB  database.Database
	RDB database.Cache
}

type GeneralControllers struct {
	UserController        *user.GeneralUserController
	CorporationController *corporation.GeneralCorporationController
}

type MemberControllers struct {
	CorporationController *corporation.MemberCorporationController
}

type Controllers struct {
	General *GeneralControllers
	Member  *MemberControllers
}

type Middlewares struct {
	CORS         *middleware.CORSMiddleware
	Recovery     *middleware.RecoveryMiddleware
	Localization *middleware.LocalizationMiddleware
	RateLimit    *middleware.RateLimitMiddleware
	Logger       *middleware.LoggerMiddleware
	Prometheus   *middleware.PrometheusMiddleware
	Auth         *middleware.AuthMiddleware
}

type Application struct {
	Database    *Database
	Controllers *Controllers
	Middlewares *Middlewares
}

func NewApplication(database2 *Database,
	controllers *Controllers,
	middlewares *Middlewares,
) *Application {
	return &Application{
		Database:    database2,
		Controllers: controllers,
		Middlewares: middlewares,
	}
}
