// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/BargheNo/Backend/bootstrap"
	"github.com/BargheNo/Backend/internal/application/adapter/jwt"
	"github.com/BargheNo/Backend/internal/application/adapter/localization"
	"github.com/BargheNo/Backend/internal/application/adapter/logger"
	"github.com/BargheNo/Backend/internal/application/adapter/metrics"
	"github.com/BargheNo/Backend/internal/application/service"
	"github.com/BargheNo/Backend/internal/application/service/communication"
	"github.com/BargheNo/Backend/internal/application/service/interfaces"
	"github.com/BargheNo/Backend/internal/domain/logger"
	"github.com/BargheNo/Backend/internal/domain/metrics"
	"github.com/BargheNo/Backend/internal/domain/repository/postgres"
	"github.com/BargheNo/Backend/internal/domain/repository/redis"
	"github.com/BargheNo/Backend/internal/domain/s3"
	"github.com/BargheNo/Backend/internal/infrastructure/cin"
	"github.com/BargheNo/Backend/internal/infrastructure/database"
	"github.com/BargheNo/Backend/internal/infrastructure/repository/postgres"
	"github.com/BargheNo/Backend/internal/infrastructure/repository/redis"
	"github.com/BargheNo/Backend/internal/infrastructure/seed"
	"github.com/BargheNo/Backend/internal/infrastructure/storage"
	"github.com/BargheNo/Backend/internal/infrastructure/websocket"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/address"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/bid"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/chat"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/corporation"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/installation"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/maintenance"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/notification"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/user"
	"github.com/BargheNo/Backend/internal/presentation/middleware"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config, hub *websocket.Hub) (*Application, error) {
	bootstrapDatabase := ProvideDBConfig(container)
	postgresDatabase := database.NewPostgresDatabase(bootstrapDatabase)
	redis := ProvideRDBConfig(container)
	redisDatabase := database.NewRedisDatabase(redis)
	wireDatabase := &Database{
		DB:  postgresDatabase,
		RDB: redisDatabase,
	}
	constants := ProvideConstants(container)
	otp := ProvideOTPConfig(container)
	userCacheRepository := cacherepositoryimpl.NewUserCacheRepository(redisDatabase)
	otpService := serviceimpl.NewOTPService(constants, otp, userCacheRepository)
	keyManager := jwtimpl.NewJWTKeyManager()
	jwtKeysPath := ProvideJWTKeysPath(container)
	jwtService := serviceimpl.NewJWTService(keyManager, jwtKeysPath)
	smsGateway := ProvideSMSGatewayConfig(container)
	smsTemplates := ProvideSMSTemplates(container)
	smsService := communicationService.NewSMSService(smsGateway, smsTemplates)
	s3 := ProvideStorageConfig(container)
	s3Storage := storage.NewS3Storage(constants, s3)
	userRepository := repositoryimpl.NewUserRepository()
	userService := serviceimpl.NewUserService(constants, otpService, jwtService, smsService, s3Storage, userRepository, userCacheRepository, postgresDatabase)
	generalUserController := user.NewGeneralUserController(constants, userService, jwtService)
	addressRepository := repositoryimpl.NewAddressRepository()
	addressService := serviceimpl.NewAddressService(constants, addressRepository, postgresDatabase)
	generalAddressController := address.NewGeneralAddressController(constants, addressService)
	corporationRepository := repositoryimpl.NewCorporationRepository()
	corporationService := serviceimpl.NewCorporationService(constants, userService, addressService, s3Storage, corporationRepository, postgresDatabase)
	generalCorporationController := corporation.NewGeneralCorporationController(constants, corporationService)
	generalControllers := &GeneralControllers{
		UserController:        generalUserController,
		AddressController:     generalAddressController,
		CorporationController: generalCorporationController,
	}
	customerUserController := user.NewCustomerUserController(constants, userService)
	pagination := ProvidePaginationConfig(container)
	installationRepository := repositoryimpl.NewInstallationRepository()
	installationService := serviceimpl.NewInstallationService(constants, addressService, userService, corporationService, installationRepository, postgresDatabase)
	customerInstallationController := installation.NewCustomerInstallationController(constants, pagination, installationService)
	customerAddressController := address.NewCustomerAddressController(constants, addressService)
	customerCorporationController := corporation.NewCustomerCorporationController(constants, pagination, corporationService)
	bidRepository := repositoryimpl.NewBidRepository()
	bidService := serviceimpl.NewBidService(constants, installationService, userService, corporationService, bidRepository, postgresDatabase)
	customerBidController := bid.NewCustomerBidController(constants, pagination, bidService)
	websocketSetting := ProvideWebsocketSetting(container)
	chatRepository := repositoryimpl.NewChatRepository()
	chatService := serviceimpl.NewChatService(constants, userService, corporationService, chatRepository, postgresDatabase)
	customerChatController := chat.NewCustomerChatController(constants, websocketSetting, chatService, jwtService, hub)
	notificationRepository := repositoryimpl.NewNotificationRepository()
	notificationService := serviceimpl.NewNotificationService(constants, userService, notificationRepository, hub, postgresDatabase)
	customerNotificationController := notification.NewCustomerNotificationController(constants, websocketSetting, notificationService, jwtService, hub)
	maintenanceRepository := repositoryimpl.NewMaintenanceRepository()
	maintenanceService := serviceimpl.NewMaintenanceService(constants, userService, installationService, corporationService, addressService, maintenanceRepository, postgresDatabase)
	customerMaintenanceController := maintenance.NewCustomerMaintenanceController(constants, pagination, maintenanceService)
	customerControllers := &CustomerControllers{
		UserController:         customerUserController,
		InstallationController: customerInstallationController,
		AddressController:      customerAddressController,
		CorporationController:  customerCorporationController,
		BidController:          customerBidController,
		ChatController:         customerChatController,
		NotificationController: customerNotificationController,
		MaintenanceController:  customerMaintenanceController,
	}
	corporationCorporationController := corporation.NewCorporationCorporationController(constants, pagination, corporationService)
	corporationInstallationController := installation.NewCorporationInstallationController(constants, pagination, installationService)
	corporationBidController := bid.NewCorporationBidController(constants, pagination, bidService)
	corporationMaintenanceController := maintenance.NewCorporationMaintenanceController(constants, pagination, maintenanceService)
	corporationControllers := &CorporationControllers{
		CorporationController:  corporationCorporationController,
		InstallationController: corporationInstallationController,
		BidController:          corporationBidController,
		MaintenanceController:  corporationMaintenanceController,
	}
	controllers := &Controllers{
		General:     generalControllers,
		Customer:    customerControllers,
		Corporation: corporationControllers,
	}
	authMiddleware := middleware.NewAuthMiddleware(constants, jwtService, userRepository, postgresDatabase)
	corsMiddleware := middleware.NewCorsMiddleware()
	recoveryMiddleware := middleware.NewRecovery(constants)
	translator := localizationimpl.NewTranslationService()
	localizationMiddleware := middleware.NewLocalization(constants, translator)
	rateLimit := ProvideRateLimitConfig(container)
	rateLimitMiddleware := middleware.NewRateLimit(rateLimit)
	logger := ProvideLoggerConfig(container)
	loggerimplLogger, err := loggerimpl.NewLogger(logger, constants)
	if err != nil {
		return nil, err
	}
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerimplLogger)
	metrics := ProvideMetrics(container)
	prometheusMetrics := metricsimpl.NewPrometheusMetrics(metrics)
	prometheusMiddleware := middleware.NewPrometheusMiddleware(prometheusMetrics)
	websocketMiddleware := middleware.NewWebsocketMiddleware(constants)
	middlewares := &Middlewares{
		Authentication:      authMiddleware,
		CORS:                corsMiddleware,
		Recovery:            recoveryMiddleware,
		Localization:        localizationMiddleware,
		RateLimit:           rateLimitMiddleware,
		Logger:              loggerMiddleware,
		Prometheus:          prometheusMiddleware,
		WebsocketMiddleware: websocketMiddleware,
	}
	addressSeeder := seed.NewAddressSeeder(addressRepository, postgresDatabase)
	notificationTypeSeeder := seed.NewNotificationTypeSeeder(notificationRepository, postgresDatabase)
	seeds := &Seeds{
		AddressSeeder:          addressSeeder,
		NotificationTypeSeeder: notificationTypeSeeder,
	}
	application := NewApplication(wireDatabase, controllers, middlewares, seeds)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(database.NewPostgresDatabase, database.NewRedisDatabase, wire.Bind(new(database.Database), new(*database.PostgresDatabase)), wire.Bind(new(database.Cache), new(*database.RedisDatabase)), wire.Struct(new(Database), "*"))

var RepositoryProviderSet = wire.NewSet(repositoryimpl.NewUserRepository, repositoryimpl.NewInstallationRepository, repositoryimpl.NewAddressRepository, cacherepositoryimpl.NewUserCacheRepository, repositoryimpl.NewCorporationRepository, repositoryimpl.NewBidRepository, repositoryimpl.NewChatRepository, repositoryimpl.NewNotificationRepository, repositoryimpl.NewMaintenanceRepository, wire.Bind(new(repository.UserRepository), new(*repositoryimpl.UserRepository)), wire.Bind(new(repository.InstallationRepository), new(*repositoryimpl.InstallationRepository)), wire.Bind(new(repository.AddressRepository), new(*repositoryimpl.AddressRepository)), wire.Bind(new(cacherepository.UserCacheRepository), new(*cacherepositoryimpl.UserCacheRepository)), wire.Bind(new(repository.CorporationRepository), new(*repositoryimpl.CorporationRepository)), wire.Bind(new(repository.BidRepository), new(*repositoryimpl.BidRepository)), wire.Bind(new(repository.ChatRepository), new(*repositoryimpl.ChatRepository)), wire.Bind(new(repository.NotificationRepository), new(*repositoryimpl.NotificationRepository)), wire.Bind(new(repository.MaintenanceRepository), new(*repositoryimpl.MaintenanceRepository)))

var ServiceProviderSet = wire.NewSet(serviceimpl.NewUserService, serviceimpl.NewOTPService, communicationService.NewSMSService, serviceimpl.NewJWTService, serviceimpl.NewInstallationService, serviceimpl.NewAddressService, serviceimpl.NewCorporationService, cinimpl.NewCINService, serviceimpl.NewBidService, serviceimpl.NewChatService, serviceimpl.NewNotificationService, serviceimpl.NewMaintenanceService, wire.Bind(new(service.UserService), new(*serviceimpl.UserService)), wire.Bind(new(service.OTPService), new(*serviceimpl.OTPService)), wire.Bind(new(service.SMSService), new(*communicationService.SMSService)), wire.Bind(new(service.JWTService), new(*serviceimpl.JWTService)), wire.Bind(new(service.InstallationService), new(*serviceimpl.InstallationService)), wire.Bind(new(service.AddressService), new(*serviceimpl.AddressService)), wire.Bind(new(service.CorporationService), new(*serviceimpl.CorporationService)), wire.Bind(new(service.CINService), new(*cinimpl.CINService)), wire.Bind(new(service.BidService), new(*serviceimpl.BidService)), wire.Bind(new(service.ChatService), new(*serviceimpl.ChatService)), wire.Bind(new(service.NotificationService), new(*serviceimpl.NotificationService)), wire.Bind(new(service.MaintenanceService), new(*serviceimpl.MaintenanceService)))

var AdapterProviderSet = wire.NewSet(localizationimpl.NewTranslationService, loggerimpl.NewLogger, jwtimpl.NewJWTKeyManager, metricsimpl.NewPrometheusMetrics, storage.NewS3Storage, wire.Bind(new(logger.Logger), new(*loggerimpl.Logger)), wire.Bind(new(metrics.MetricsClient), new(*metricsimpl.PrometheusMetrics)), wire.Bind(new(s3.S3Storage), new(*storage.S3Storage)))

var GeneralControllerProviderSet = wire.NewSet(user.NewGeneralUserController, address.NewGeneralAddressController, corporation.NewGeneralCorporationController, wire.Struct(new(GeneralControllers), "*"))

var CustomerControllerProviderSet = wire.NewSet(user.NewCustomerUserController, installation.NewCustomerInstallationController, address.NewCustomerAddressController, corporation.NewCustomerCorporationController, bid.NewCustomerBidController, chat.NewCustomerChatController, notification.NewCustomerNotificationController, maintenance.NewCustomerMaintenanceController, wire.Struct(new(CustomerControllers), "*"))

var CorporationControllerProviderSet = wire.NewSet(corporation.NewCorporationCorporationController, installation.NewCorporationInstallationController, bid.NewCorporationBidController, maintenance.NewCorporationMaintenanceController, wire.Struct(new(CorporationControllers), "*"))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewareProviderSet = wire.NewSet(middleware.NewAuthMiddleware, middleware.NewCorsMiddleware, middleware.NewRecovery, middleware.NewLocalization, middleware.NewRateLimit, middleware.NewLoggerMiddleware, middleware.NewPrometheusMiddleware, middleware.NewWebsocketMiddleware, wire.Struct(new(Middlewares), "*"))

var SeederProviderSet = wire.NewSet(seed.NewAddressSeeder, seed.NewNotificationTypeSeeder, wire.Struct(new(Seeds), "*"))

func ProvideConstants(container *bootstrap.Config) *bootstrap.Constants {
	return container.Constants
}

func ProvideLoggerConfig(container *bootstrap.Config) *bootstrap.Logger {
	return &container.Env.Logger
}

func ProvideRateLimitConfig(container *bootstrap.Config) *bootstrap.RateLimit {
	return &container.Env.RateLimit
}

func ProvideDBConfig(container *bootstrap.Config) *bootstrap.Database {
	return &container.Env.PrimaryDB
}

func ProvideRDBConfig(container *bootstrap.Config) *bootstrap.Redis {
	return &container.Env.PrimaryRedis
}

func ProvideOTPConfig(container *bootstrap.Config) *bootstrap.OTP {
	return &container.Env.OTP
}

func ProvideSMSGatewayConfig(container *bootstrap.Config) *bootstrap.SMSGateway {
	return &container.Env.SMSGateway
}

func ProvideSMSTemplates(container *bootstrap.Config) *bootstrap.SMSTemplates {
	return &container.Constants.SMSTemplates
}

func ProvideJWTKeysPath(container *bootstrap.Config) *bootstrap.JWTKeysPath {
	return &container.Constants.JWTKeysPath
}

func ProvideMetrics(container *bootstrap.Config) *bootstrap.Metrics {
	return &container.Constants.Metrics
}

func ProvidePaginationConfig(container *bootstrap.Config) *bootstrap.Pagination {
	return &container.Env.Pagination
}

func ProvideStorageConfig(container *bootstrap.Config) *bootstrap.S3 {
	return &container.Env.Storage
}

func ProvideWebsocketSetting(container *bootstrap.Config) *bootstrap.WebsocketSetting {
	return &container.Env.WebsocketSetting
}

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	RepositoryProviderSet,
	ServiceProviderSet,
	AdapterProviderSet,
	GeneralControllerProviderSet,
	CustomerControllerProviderSet,
	CorporationControllerProviderSet,
	ControllersProviderSet,
	MiddlewareProviderSet,
	SeederProviderSet,
	ProvideConstants,
	ProvideLoggerConfig,
	ProvideRateLimitConfig,
	ProvideDBConfig,
	ProvideRDBConfig,
	ProvideOTPConfig,
	ProvideSMSGatewayConfig,
	ProvideSMSTemplates,
	ProvideJWTKeysPath,
	ProvideMetrics,
	ProvidePaginationConfig,
	ProvideStorageConfig,
	ProvideWebsocketSetting,
)

type Database struct {
	DB  database.Database
	RDB database.Cache
}

type GeneralControllers struct {
	UserController        *user.GeneralUserController
	AddressController     *address.GeneralAddressController
	CorporationController *corporation.GeneralCorporationController
}

type CustomerControllers struct {
	UserController         *user.CustomerUserController
	InstallationController *installation.CustomerInstallationController
	AddressController      *address.CustomerAddressController
	CorporationController  *corporation.CustomerCorporationController
	BidController          *bid.CustomerBidController
	ChatController         *chat.CustomerChatController
	NotificationController *notification.CustomerNotificationController
	MaintenanceController  *maintenance.CustomerMaintenanceController
}

type CorporationControllers struct {
	CorporationController  *corporation.CorporationCorporationController
	InstallationController *installation.CorporationInstallationController
	BidController          *bid.CorporationBidController
	MaintenanceController  *maintenance.CorporationMaintenanceController
}

type Controllers struct {
	General     *GeneralControllers
	Customer    *CustomerControllers
	Corporation *CorporationControllers
}

type Middlewares struct {
	Authentication      *middleware.AuthMiddleware
	CORS                *middleware.CORSMiddleware
	Recovery            *middleware.RecoveryMiddleware
	Localization        *middleware.LocalizationMiddleware
	RateLimit           *middleware.RateLimitMiddleware
	Logger              *middleware.LoggerMiddleware
	Prometheus          *middleware.PrometheusMiddleware
	WebsocketMiddleware *middleware.WebsocketMiddleware
}

type Seeds struct {
	AddressSeeder          *seed.AddressSeeder
	NotificationTypeSeeder *seed.NotificationTypeSeeder
}

type Application struct {
	Database    *Database
	Controllers *Controllers
	Middlewares *Middlewares
	Seeds       *Seeds
}

func NewApplication(database2 *Database,
	controllers *Controllers,
	middlewares *Middlewares,
	seeds *Seeds,
) *Application {
	return &Application{
		Database:    database2,
		Controllers: controllers,
		Middlewares: middlewares,
		Seeds:       seeds,
	}
}
