// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/BargheNo/Backend/bootstrap"
	"github.com/BargheNo/Backend/internal/application/adapter/localization"
	"github.com/BargheNo/Backend/internal/application/adapter/logger"
	"github.com/BargheNo/Backend/internal/application/service"
	"github.com/BargheNo/Backend/internal/application/service/interfaces"
	"github.com/BargheNo/Backend/internal/domain/logger"
	"github.com/BargheNo/Backend/internal/domain/repository"
	"github.com/BargheNo/Backend/internal/infrastructure/database"
	"github.com/BargheNo/Backend/internal/infrastructure/repository"
	"github.com/BargheNo/Backend/internal/presentation/controller/v1/sample"
	"github.com/BargheNo/Backend/internal/presentation/middleware"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config, db database.Database) (*Application, error) {
	constants := ProvideConstants(container)
	sampleRepository := repositoryimpl.NewSampleRepository()
	sampleService := serviceimpl.NewSampleService(constants, sampleRepository, db)
	sampleController := sample.NewSampleController(constants, sampleService)
	controllers := &Controllers{
		SampleController: sampleController,
	}
	recoveryMiddleware := middleware.NewRecovery(constants)
	translator := localizationimpl.NewTranslationService()
	localizationMiddleware := middleware.NewLocalization(constants, translator)
	rateLimit := ProvideRateLimitConfig(container)
	rateLimitMiddleware := middleware.NewRateLimit(rateLimit)
	logger := ProvideLoggerConfig(container)
	loggerimplLogger, err := loggerimpl.NewLogger(logger, constants)
	if err != nil {
		return nil, err
	}
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerimplLogger)
	middlewares := &Middlewares{
		Recovery:     recoveryMiddleware,
		Localization: localizationMiddleware,
		RateLimit:    rateLimitMiddleware,
		Logger:       loggerMiddleware,
	}
	application := NewApplication(controllers, middlewares)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(repositoryimpl.NewSampleRepository, wire.Bind(new(repository.SampleRepository), new(*repositoryimpl.SampleRepository)))

var ServiceProviderSet = wire.NewSet(serviceimpl.NewSampleService, wire.Bind(new(service.SampleService), new(*serviceimpl.SampleService)))

var AdapterProviderSet = wire.NewSet(localizationimpl.NewTranslationService, loggerimpl.NewLogger, wire.Bind(new(logger.Logger), new(*loggerimpl.Logger)))

var ControllerProviderSet = wire.NewSet(sample.NewSampleController, wire.Struct(new(Controllers), "*"))

var MiddlewareProviderSet = wire.NewSet(middleware.NewRecovery, middleware.NewLocalization, middleware.NewRateLimit, middleware.NewLoggerMiddleware, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Config) *bootstrap.Constants {
	return container.Constants
}

func ProvideLoggerConfig(container *bootstrap.Config) *bootstrap.Logger {
	return &container.Env.Logger
}

func ProvideRateLimitConfig(container *bootstrap.Config) *bootstrap.RateLimit {
	return &container.Env.RateLimit
}

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	ServiceProviderSet,
	AdapterProviderSet,
	ControllerProviderSet,
	MiddlewareProviderSet,
	ProvideConstants,
	ProvideLoggerConfig,
	ProvideRateLimitConfig,
)

type Controllers struct {
	SampleController *sample.SampleController
}

type Middlewares struct {
	Recovery     *middleware.RecoveryMiddleware
	Localization *middleware.LocalizationMiddleware
	RateLimit    *middleware.RateLimitMiddleware
	Logger       *middleware.LoggerMiddleware
}

type Application struct {
	Controllers *Controllers
	Middlewares *Middlewares
}

func NewApplication(
	controllers *Controllers,
	middlewares *Middlewares,
) *Application {
	return &Application{
		Controllers: controllers,
		Middlewares: middlewares,
	}
}
