package service

import (
	maintenancedto "github.com/BargheNo/Backend/internal/application/dto/maintenance"
	"github.com/BargheNo/Backend/internal/domain/enum"
)

type MaintenanceService interface {
	GetMaintenanceUrgencyLevels() []maintenancedto.MaintenanceStatusesResponse
	GetMaintenanceRequestStatuses(agent enum.AgentType) []maintenancedto.MaintenanceStatusesResponse
	CreateMaintenanceRequest(requestInfo maintenancedto.CreateMaintenanceRequest)
	GetCustomerMaintenanceRequests(requestInfo maintenancedto.CustomerMaintenanceListRequest) []maintenancedto.CustomerMaintenanceRequestResponse
	GetCustomerPanelMaintenanceRequests(listInfo maintenancedto.CustomerPanelMaintenanceListRequest) []maintenancedto.CustomerMaintenanceRequestResponse
	GetCustomerMaintenanceRequest(maintenanceInfo maintenancedto.CustomerMaintenanceRequest) maintenancedto.CustomerMaintenanceRequestResponse
	UpdateMaintenanceRequest(updateRequest maintenancedto.UpdateCustomerRequest)
	CancelMaintenanceRequest(maintenanceInfo maintenancedto.CustomerMaintenanceRequest)
	ApproveMaintenanceRecord(maintenanceInfo maintenancedto.CustomerMaintenanceRequest)
	GetCorporationMaintenanceRequests(listInfo maintenancedto.CorporationMaintenanceListRequest) []maintenancedto.CorporationMaintenanceListResponse
	GetCorporationMaintenanceRequest(maintenanceInfo maintenancedto.CorporationMaintenanceRequest) maintenancedto.CorporationMaintenanceResponse
	AcceptMaintenanceRequest(maintenanceInfo maintenancedto.CorporationMaintenanceRequest)
	RejectMaintenanceRequest(maintenanceInfo maintenancedto.CorporationMaintenanceRequest)
	CreateMaintenanceRecord(recordInfo maintenancedto.CreateMaintenanceRecordRequest)
	UpdateMaintenanceRecord(recordInfo maintenancedto.UpdateMaintenanceRecordRequest)
	ValidateCustomerRecord(recordID, userID uint) error
	GetRequestByAdmin(recordID uint) (maintenancedto.AdminMaintenanceRequestResponse, error)
}
