package service

import maintenancedto "github.com/BargheNo/Backend/internal/application/dto/maintenance"

type MaintenanceService interface {
	CreateMaintenanceRequest(requestInfo maintenancedto.NewMaintenanceRequest)
	GetCustomerMaintenanceRequests(requestInfo maintenancedto.MaintenanceListRequest) []maintenancedto.CustomerMaintenanceRequestResponse
	GetCorporationMaintenanceRequests(requestInfo maintenancedto.CorporationMaintenanceListRequest) []maintenancedto.CorporationMaintenanceResponse
	HandleRequest(requestInfo maintenancedto.HandleRequest)
	AddMaintenanceRecord(requestInfo maintenancedto.AddMaintenanceRecordRequest)
	GetCorporationMaintenanceRecords(requestInfo maintenancedto.CorporationMaintenanceListRequest) []maintenancedto.CorporationMaintenanceRecordResponse
	GetCorporationMaintenanceRecordsByPanel(requestInfo maintenancedto.CorporationMaintenanceRecordByPanelRequest) []maintenancedto.CorporationMaintenanceRecordResponse
	GetCustomerMaintenanceRecords(requestInfo maintenancedto.MaintenanceListRequest) []maintenancedto.CustomerMaintenanceRecordResponse
	GetCustomerMaintenanceRecordsByPanel(requestInfo maintenancedto.CustomerMaintenanceRecordByPanelRequest) []maintenancedto.CustomerMaintenanceRecordResponse
	GetMaintenanceRecordByID(maintenanceID uint) maintenancedto.MaintenanceRecordResponse
}
